/**
 * Recruit API
 * API for recruitment platform
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StatusType } from './statusType';

export interface CreateNotificationDto {
  /**
   * Name of the candidate
   */
  name: string;
  status: StatusType;
  /**
   * Position of the candidate
   */
  position: string;
  /**
   * Email of the candidate
   */
  email: string;
}
export namespace CreateNotificationDto {}
